hparams:
    max_epochs: 30
    batch_size: 128
    learning_rate: 0.001
    accumulate_grad_batches: 1
    gradient_clip_val: 0.5
    num_of_gpus: 1
    model:
        lin1_size: 128
        lin2_size: 256
        lin3_size: 128
    dataset:
        use_val: True
        val_size: 5_000
        use_test: True
        test_size: 10_000

resume:
    resume_from_ckpt: False
    ckpt_path: "logs/checkpoints/model-epoch=04-val_loss=3.85.ckpt"

loggers:
    wandb:
        project: "hackathon_template_test"
        team: "kino"
        group: None
        job_type: "train"
        tags: []

callbacks:
    checkpoint:
        monitor: "val_loss"
        save_top_k: 1
        save_last: True
        mode: "min"
    early_stop:
        monitor: "val_loss"
        patience: 10
        mode: "min"

printing:
    progress_bar_refresh_rate: 50
    weights_summary: "full"
    profiler: True
