num_of_gpus: -1

hparams:
    max_epochs: 20
    batch_size: 64
    lr: 0.001
    accumulate_grad_batches: 1
    gradient_clip_val: 0.5
    lin1_size: 128
    lin2_size: 256
    lin3_size: 128

resume:
    resume_from_ckpt: False
    ckpt_path: "logs/checkpoints/model-epoch=04-val_loss=3.85.ckpt"

loggers:
    wandb:
        project: "hackathon_template_test"
        team: "kino"
        group: None
        job_type: "train"
        tags: []

callbacks:
    checkpoint:
        monitor: "val_loss"
        save_top_k: 1
        save_last: False
        mode: "min"
    early_stop:
        monitor: "val_loss"
        patience: 100
        mode: "min"

printing:
    progress_bar_refresh_rate: 50
    weights_summary: "full"
    profiler: True
