# @package _global_

defaults:
    - trainer: default_trainer.yaml
    - model: simple_mnist_classifier.yaml
    - datamodule: mnist_datamodule.yaml
    - callbacks: default_callbacks.yaml
    - loggers: null


paths:
    data_dir: "data/"   # path to data folder (either absolute or relative to placement of 'train.py' file)
    logs_dir: "logs/"   # path to logs folder (either absolute or relative to placement of 'train.py' file)


hydra:
    run:
        dir: ${paths.logs_dir}/hydra_logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: ${paths.logs_dir}/hydra_logs/sweeps/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}
