EarlyStopping:  # name of PyTorch Lightning class for early stopping callback
    monitor: "val_acc"
    patience: 5
    mode: "max"

ModelCheckpoint:  # name of PyTorch Lightning class for checkpointing callback
    monitor: "val_acc"
    save_top_k: 1
    save_last: True
    mode: "max"

ConfusionMatrixWandbLoggerCallback:  # some custom callback class from template_utils/wandb_callbacks.py
    class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

MetricsHeatmapWandbLoggerCallback:  # some custom callback class from template_utils/wandb_callbacks.py
    class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
