# @package _group_

class: "pytorch_modules.lightning_models.simple_mnist_classifier.LitModel"
args:
    lr: 0.001
    weight_decay: 0.00001
    input_size: 784
    output_size: 10
    lin1_size: 256
    lin2_size: 256
    lin3_size: 128

