# @package _group_

save_best_metric_scores_to_wandb:
    class: pytorch_modules.lightning_callbacks.wandb_callbacks.SaveBestMetricScoresToWandb
    args: {}


save_code_to_wandb_as_artifact:
    class: pytorch_modules.lightning_callbacks.wandb_callbacks.SaveCodeToWandb
    args:
        code_dir: ${work_dir}/


upload_ckpts_to_wandb_as_artifact:
    class: pytorch_modules.lightning_callbacks.wandb_callbacks.UploadAllCheckpointsToWandb
    args:
        ckpt_dir: "checkpoints/"
        upload_best_only: True
