num_of_gpus: -1

hparams:
    max_epochs: 30
    batch_size: 64
    lr: 0.001
    accumulate_grad_batches: 1
    gradient_clip_val: 0.5
    lin1_size: 128
    lin2_size: 256
    lin3_size: 128

resume:
    resume_from_ckpt: False
    wandb_run_id: "8uuomodb"
    ckpt_path: "wandb/run-20201111_022721-8uuomodb/files/hackathon_template_test/8uuomodb/checkpoints/epoch=2.ckpt"

loggers:
    wandb:
        project: "hackathon_template_test"
        team: "kino"
        group: None
        job_type: "train"
        tags: []

callbacks:
    checkpoint:
        monitor: "val_acc"
        save_top_k: 1
        save_last: True
        mode: "max"
    early_stop:
        monitor: "val_acc"
        patience: 100
        mode: "max"

printing:
    progress_bar_refresh_rate: 20
    weights_summary: "full"
    profiler: True
