MNIST_CLASSIFIER_V1:
    trainer:
        max_epochs: 5
    model:
        name: "simple_mnist_classifier"
        lr: 0.001
        weight_decay: 0.000001
        input_size: 784  # img size is 28*28*1
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128
    dataset:
        name: "MNISTDataModule"
        batch_size: 64
        train_val_split_ratio: 0.9

CIFAR10_CLASSIFIER_V1:
    trainer:
        max_epochs: 5
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
    model:
        name: "transfer_learning_img_classifier"
        lr: 0.001
        weight_decay: 0.000001
        output_size: 10
        lin1_size: 256
        lin2_size: 128
    dataset:
        name: "CIFAR10DataModule"
        batch_size: 64
        train_val_split_ratio: 0.9
        num_workers: 1
        pin_memory: False

CIFAR10_CLASSIFIER_V2:
    trainer:
        max_epochs: 10
        gradient_clip_val: 0.5
        accumulate_grad_batches: 2
        limit_train_batches: 1.0
    model:
        name: "transfer_learning_img_classifier"
        lr: 0.002
        weight_decay: 0.00001
        output_size: 10
        lin1_size: 512
        lin2_size: 256
    dataset:
        name: "CIFAR10DataModule"
        batch_size: 256
        train_val_split_ratio: 0.9
        num_workers: 4
        pin_memory: True
