model: "simple_mnist_classifier"
data: "MNISTDataModule"

num_of_gpus: -1

dataset_params:
    MNISTDataModule:
        train_val_split_ratio: 0.9
        num_workers: 4
        pin_memory: True
    CIFAR10DataModule:
        train_val_split_ratio: 0.9
        num_workers: 4
        pin_memory: True

loggers:
    wandb:
        project: "hackathon_template_test"
        team: "kino"
        group: None
        job_type: "train"
        tags: []
        log_model: True
        offline: False

callbacks:
    checkpoint:
        monitor: "val_acc"
        save_top_k: 1
        save_last: True
        mode: "max"
    early_stop:
        monitor: "val_acc"
        patience: 100
        mode: "max"

printing:
    progress_bar_refresh_rate: 5
    weights_summary: "top"  # "full"
    profiler: False
