# @package _group_
# Comet logger config

args:
    api_key: "sadfhgadfhsdfhadgkajdgsdg"
    project_name: "project_template_test"

extra_options:
    log_optimizer_name: True
    log_train_val_test_sizes: True
