_target_: src.models.ebay_module.eBayCosFaceModule
lr: 0.0001
weight_decay: 0.0005
ce_margin: 0.2
ce_margin_type: cos

net:
  _target_: src.models.components.torchvision_image_encoder.TorchvisionImageEncoder
  name: resnet50
