_target_: src.models.ebay_module.eBayPureContrastiveModule
lr: 0.0002
weight_decay: 0.0005
text_lr_multiplier: 0.1
output_dim: 2048

net:
  _target_: src.models.components.torchvision_image_encoder.TorchvisionImageEncoder
  name: resnet50

text_net:
  _target_: src.models.components.text_encoder.RoBERTa
  name: roberta-base
