_target_: src.models.ebay_module.eBayModule
lr: 0.0001
weight_decay: 0.0005
loss_1: 1.0
loss_2: 1.0
loss_3: 1.0
linear_dim: 0

net:
  _target_: src.models.components.torchvision_image_encoder.TorchvisionImageEncoder
  name: resnet50
