# to execute this experiment run:
# python train.py --exp_conf configs/experiment/mnist_experiments/simple_conf.yaml


seed: 1234

trainer_args:
    max_epochs: 10

model:
    class: "pytorch_modules.lightning_models.simple_mnist_classifier.LitModel"
    hparams:
        lr: 0.001
        weight_decay: 0.00001
        input_size: 784
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128

datamodule:
    class: "lightning_datamodules.mnist_datamodule.mnist_datamodule.MNISTDataModule"
    hparams:
        batch_size: 64
        train_val_test_split: [55_000, 5_000, 10_000]
