# to execute this run:
# python train.py --run_config_name SIMPLE_CONFIG_EXAMPLE_MNIST

seed: 1234

trainer_args:
    max_epochs: 10

model:
    load_from:
        model_path: "lightning_models/simple_mnist_classifier/simple_mnist_classifier.py"
        model_class: "LitModel"
    hparams:
        lr: 0.001
        weight_decay: 0.00001
        input_size: 784
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128

datamodule:
    load_from:
        datamodule_path: "lightning_datamodules/mnist_datamodule/mnist_datamodule.py"
        datamodule_class: "MNISTDataModule"
    hparams:
        batch_size: 64
        train_val_test_split: [55_000, 5_000, 10_000]
