# @package _global_

defaults:
  - _self_
  - log_dir: ensemble.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

feature_dirs:
  - logs/evaluations/runs/multilabel_convnextxl_ema/2022-05-03_04-37-41/
  - logs/evaluations/runs/multilabel_swinl_ema_poly/2022-05-05_01-15-24/
  - logs/evaluations/runs/multilabel_swinl_ema_poly_0.5/2022-05-06_21-02-23/

csv_save_dir: ${hydra:run.dir}

print_config: True

ignore_warnings: True

whitening: True

re_ranking: True
