# @package _global_

defaults:
  - _self_
  - log_dir: ensemble.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

feature_dirs:
  - logs/evaluations/runs/multilabel_convnextxl_drop/2022-04-28_21-03-03/
  - logs/evaluations/runs/multilabel_convnextxl_droppath/2022-04-28_22-01-53/
  - logs/evaluations/runs/multilabel_swinl/2022-04-27_23-59-16/
  - logs/evaluations/runs/multilabel_convnextxl_ema/2022-05-03_04-37-41/

csv_save_dir: ${hydra:run.dir}

print_config: True

ignore_warnings: True

whitening: True

re_ranking: True
