# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: ebay.yaml # choose the datamodule for evaluation
  - model: three_classes.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/eBay

csv_save_dir: ${hydra:run.dir}

similarity_metric: euclidean

print_config: True

ignore_warnings: True

seed: null

name: "baseline"

# passing checkpoint path is necessary
ckpt_path: ???

save_sim: False

whitening: False

re_ranking: False
