_target_: src.datamodules.ebay_datamodule.eBayDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
num_workers: 8
pin_memory: True
train_transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
val_transforms:
  - _target_: torchvision.transforms.Resize
    size: [316, 316]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
