# @package _group_

# Neptune loggers config
neptune:
    class: pytorch_lightning.loggers.NeptuneLogger

    args: {}

    extra_options:
        log_optimizer_name: True
        log_train_val_test_sizes: True
