# @package _global_

hydra:
  run:
    dir: logs/experiments/runs/${name}/${condir_dirname}
  sweep:
    dir: logs/experiments/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
